# 알람 목록 조회
GET localhost:8080/api/v1/alarms?page=0&size=10&sort=id
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
# SSE 연결
GET localhost:8080/api/v1/alarms/subscribe?token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3Q0QHRlc3QuY29tIiwiaWF0IjoxNjY5MjE2MjM5LCJleHAiOjE2NjkyMTgwMzl9.M0-B-47SP8aW1WTxEoQcrPFyK5VWZ2wc6c5juACg3-k
Content-Type: application/json