spring:
  cache:
    type: redis
  thymeleaf3:
    decoupled-logic: true
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
#  data:
#    rest:
#      base-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    study.application.project: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descripter.sql.BasicBinder: trace