spring:
  cache:
    type: redis
  thymeleaf:
    cache: false # 개발 시 thymeleaf 변화를 바로 확인하고 싶은데 캐시가 설정되어 있으면 캐시 내용이 반영되어 변경 사항을 확인할 수 없는 경우가 생김, prod 때 true로 변경
  thymeleaf3:
    decoupled-logic: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    study.application.project: debug
    org.springframework.web.servlet: debug