spring:
  cache:
    type: redis
  thymeleaf3:
    decoupled-logic: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    study.application.project: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descripter.sql.BasicBinder: trace