spring:
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    study.application.project: debug
    org.springframework.web.servlet: debug